# PASO 1: Data Understanding (Entendimiento de Datos)

En este paso realizaremos una exploración inicial del dataset sin realizar transformaciones, limpieza ni imputación. El objetivo es entender la estructura, tipos de datos, calidad y características principales del dataset.

In [1]:
#IMPORTACION DE LIBRERIAS
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.patches import Patch
import matplotlib.colors as mcolors
import seaborn as sns

In [2]:
# Cargar datos de transacciones
df = pd.read_csv('../data/transacciones_banco.csv')
df.head()

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance,PreviousTransactionDate
0,TX000001,AC00128,14.09,2023-04-11 16:29:14,Debit,San Diego,D000380,162.198.218.92,M015,ATM,70,Doctor,81,1,5112.21,2024-11-04 08:08:08
1,TX000002,AC00455,376.24,2023-06-27 16:44:19,Debit,Houston,D000051,13.149.61.4,M052,ATM,68,Doctor,141,1,13758.91,2024-11-04 08:09:35
2,TX000003,AC00019,126.29,2023-07-10 18:16:08,Debit,Mesa,D000235,215.97.143.157,M009,Online,19,Student,56,1,1122.35,2024-11-04 08:07:04
3,TX000004,AC00070,184.50,2023-05-05 16:32:11,Debit,Raleigh,D000187,200.13.225.150,M002,Online,26,Student,25,1,8569.06,2024-11-04 08:09:06
4,TX000005,AC00411,13.45,2023-10-16 17:51:24,Credit,Atlanta,D000308,65.164.3.100,M091,Online,26,Student,198,1,7429.40,2024-11-04 08:06:39

## 1. Foto General del Dataset

Verificamos las dimensiones, nombres de columnas y primeros/últimos registros para tener una visión inicial de la estructura.

In [3]:
print("=" * 80)
print("DIMENSIONES DEL DATASET")
print("=" * 80)
print(f"Número de filas: {df.shape[0]:,}")
print(f"Número de columnas: {df.shape[1]}")
print(f"\nTotal de celdas: {df.shape[0] * df.shape[1]:,}")

print("\n" + "=" * 80)
print("NOMBRES DE COLUMNAS")
print("=" * 80)
print(df.columns.tolist())

print("\n" + "=" * 80)
print("PRIMEROS 5 REGISTROS")
print("=" * 80)
display(df.head())

print("\n" + "=" * 80)
print("ÚLTIMOS 5 REGISTROS")
print("=" * 80)
display(df.tail())

================================================================================
DIMENSIONES DEL DATASET
================================================================================
Número de filas: 2,512
Número de columnas: 16

Total de celdas: 40,192

================================================================================
NOMBRES DE COLUMNAS
================================================================================
['TransactionID', 'AccountID', 'TransactionAmount', 'TransactionDate', 'TransactionType', 'Location', 'DeviceID', 'IP Address', 'MerchantID', 'Channel', 'CustomerAge', 'CustomerOccupation', 'TransactionDuration', 'LoginAttempts', 'AccountBalance', 'PreviousTransactionDate']

================================================================================
PRIMEROS 5 REGISTROS
================================================================================

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance,PreviousTransactionDate
0,TX000001,AC00128,14.09,2023-04-11 16:29:14,Debit,San Diego,D000380,162.198.218.92,M015,ATM,70,Doctor,81,1,5112.21,2024-11-04 08:08:08
1,TX000002,AC00455,376.24,2023-06-27 16:44:19,Debit,Houston,D000051,13.149.61.4,M052,ATM,68,Doctor,141,1,13758.91,2024-11-04 08:09:35
2,TX000003,AC00019,126.29,2023-07-10 18:16:08,Debit,Mesa,D000235,215.97.143.157,M009,Online,19,Student,56,1,1122.35,2024-11-04 08:07:04
3,TX000004,AC00070,184.50,2023-05-05 16:32:11,Debit,Raleigh,D000187,200.13.225.150,M002,Online,26,Student,25,1,8569.06,2024-11-04 08:09:06
4,TX000005,AC00411,13.45,2023-10-16 17:51:24,Credit,Atlanta,D000308,65.164.3.100,M091,Online,26,Student,198,1,7429.40,2024-11-04 08:06:39

================================================================================
ÚLTIMOS 5 REGISTROS
================================================================================

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance,PreviousTransactionDate
2507,TX002508,AC00297,856.21,2023-04-26 17:09:36,Credit,Colorado Springs,D000625,21.157.41.17,M072,Branch,33,Doctor,109,1,12690.79,2024-11-04 08:11:29
2508,TX002509,AC00322,251.54,2023-03-22 17:36:48,Debit,Tucson,D000410,49.174.157.140,M029,Branch,48,Doctor,177,1,254.75,2024-11-04 08:11:42
2509,TX002510,AC00095,28.63,2023-08-21 17:08:50,Debit,San Diego,D000095,58.1.27.124,M087,Branch,56,Retired,146,1,3382.91,2024-11-04 08:08:39
2510,TX002511,AC00118,185.97,2023-02-24 16:24:46,Debit,Denver,D000634,21.190.11.223,M041,Online,23,Student,19,1,1776.91,2024-11-04 08:12:22
2511,TX002512,AC00009,243.08,2023-02-14 16:21:23,Credit,Jacksonville,D000215,59.127.135.25,M041,Online,24,Student,93,1,131.25,2024-11-04 08:07:49

## 2. Tipos de Datos

Analizamos los tipos de datos de cada columna para entender cómo están almacenados (numéricos, objetos, fechas, etc.).

In [4]:
print("=" * 80)
print("TIPOS DE DATOS POR COLUMNA")
print("=" * 80)
print(df.dtypes)

print("\n" + "=" * 80)
print("INFORMACIÓN GENERAL DEL DATASET")
print("=" * 80)
df.info()

================================================================================
TIPOS DE DATOS POR COLUMNA
================================================================================
TransactionID               object
AccountID                   object
TransactionAmount          float64
TransactionDate             object
TransactionType             object
Location                    object
DeviceID                    object
IP Address                  object
MerchantID                  object
Channel                     object
CustomerAge                  int64
CustomerOccupation          object
TransactionDuration          int64
LoginAttempts                int64
AccountBalance             float64
PreviousTransactionDate     object
dtype: object

================================================================================
INFORMACIÓN GENERAL DEL DATASET
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2512 entries, 0 to 2511
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   TransactionID            2512 non-null   object
 1   AccountID                2512 non-null   object
 2   TransactionAmount        2512 non-null   float64
 3   TransactionDate          2512 non-null   object
 4   TransactionType          2512 non-null   object
 5   Location                 2512 non-null   object
 6   DeviceID                 2512 non-null   object
 7   IP Address               2512 non-null   object
 8   MerchantID               2512 non-null   object
 9   Channel                  2512 non-null   object
 10  CustomerAge              2512 non-null   int64
 11  CustomerOccupation       2512 non-null   object
 12  TransactionDuration      2512 non-null   int64
 13  LoginAttempts            2512 non-null   int64
 14  AccountBalance           2512 non-null   float64
 15  PreviousTransactionDate  2512 non-null   object
dtypes: float64(2), int64(3), object(11)
memory usage: 314.1+ KB

## 3. Calidad Superficial de Datos

Revisamos la presencia de valores nulos y registros duplicados para evaluar la calidad inicial del dataset.

In [5]:
print("=" * 80)
print("VALORES NULOS POR COLUMNA")
print("=" * 80)
nulos = df.isnull().sum()
nulos_pct = (df.isnull().sum() / len(df)) * 100
resumen_nulos = pd.DataFrame({
    'Nulos': nulos,
    'Porcentaje': nulos_pct
})
print(resumen_nulos[resumen_nulos['Nulos'] > 0])

print(f"\nTotal de valores nulos en el dataset: {df.isnull().sum().sum():,}")
print(f"Columnas con valores nulos: {(nulos > 0).sum()} de {len(df.columns)}")

print("\n" + "=" * 80)
print("REGISTROS DUPLICADOS")
print("=" * 80)
duplicados = df.duplicated().sum()
print(f"Número de registros duplicados: {duplicados:,}")
print(f"Porcentaje de duplicados: {(duplicados / len(df)) * 100:.2f}%")

================================================================================
VALORES NULOS POR COLUMNA
================================================================================
Empty DataFrame
Columns: [Nulos, Porcentaje]
Index: []

Total de valores nulos en el dataset: 0
Columnas con valores nulos: 0 de 16

================================================================================
REGISTROS DUPLICADOS
================================================================================
Número de registros duplicados: 0
Porcentaje de duplicados: 0.00%

## 4. Resumen Estadístico de Variables Numéricas

Analizamos las estadísticas descriptivas (media, mediana, desviación estándar, min, max, cuartiles) de las variables numéricas clave.

In [6]:
print("=" * 80)
print("RESUMEN ESTADÍSTICO DE VARIABLES NUMÉRICAS")
print("=" * 80)

# Columnas numéricas de interés
columnas_numericas = ['TransactionAmount', 'AccountBalance', 'CustomerAge', 
                      'TransactionDuration', 'LoginAttempts']

# Verificar cuáles existen en el dataset
columnas_existentes = [col for col in columnas_numericas if col in df.columns]

if columnas_existentes:
    display(df[columnas_existentes].describe())
else:
    print("No se encontraron las columnas numéricas esperadas")
    print("Columnas numéricas disponibles:")
    print(df.select_dtypes(include=[np.number]).columns.tolist())

================================================================================
RESUMEN ESTADÍSTICO DE VARIABLES NUMÉRICAS
================================================================================

,TransactionAmount,AccountBalance,CustomerAge,TransactionDuration,LoginAttempts
count,2512.000000,2512.000000,2512.000000,2512.000000,2512.000000
mean,297.593778,5114.302966,44.673965,119.643312,1.124602
std,291.946243,3900.942499,17.792198,69.963757,0.602662
min,0.260000,101.250000,18.000000,10.000000,1.000000
25%,81.885000,1504.370000,27.000000,63.000000,1.000000
50%,211.140000,4735.510000,45.000000,112.500000,1.000000
75%,414.527500,7678.820000,59.000000,161.000000,1.000000
max,1919.110000,14977.990000,80.000000,300.000000,5.000000

## 5. Distribución de Frecuencias de Variables Categóricas

Exploramos las frecuencias y distribuciones de las variables categóricas principales para entender los valores más comunes.

In [7]:
print("=" * 80)
print("FRECUENCIAS DE VARIABLES CATEGÓRICAS")
print("=" * 80)

# TransactionType
if 'TransactionType' in df.columns:
    print("\nTransactionType:")
    print(df['TransactionType'].value_counts())
    print(f"Total categorías: {df['TransactionType'].nunique()}")

# Channel
if 'Channel' in df.columns:
    print("\n" + "-" * 80)
    print("\nChannel:")
    print(df['Channel'].value_counts())
    print(f"Total categorías: {df['Channel'].nunique()}")

# CustomerOccupation
if 'CustomerOccupation' in df.columns:
    print("\n" + "-" * 80)
    print("\nCustomerOccupation:")
    print(df['CustomerOccupation'].value_counts())
    print(f"Total categorías: {df['CustomerOccupation'].nunique()}")

# Location (Top 10)
if 'Location' in df.columns:
    print("\n" + "-" * 80)
    print("\nLocation (Top 10):")
    print(df['Location'].value_counts().head(10))
    print(f"Total ubicaciones únicas: {df['Location'].nunique()}")

# MerchantID (Top 10)
if 'MerchantID' in df.columns:
    print("\n" + "-" * 80)
    print("\nMerchantID (Top 10):")
    print(df['MerchantID'].value_counts().head(10))
    print(f"Total comercios únicos: {df['MerchantID'].nunique()}")

================================================================================
FRECUENCIAS DE VARIABLES CATEGÓRICAS
================================================================================

TransactionType:
TransactionType
Debit     1944
Credit     568
Name: count, dtype: int64
Total categorías: 2

--------------------------------------------------------------------------------

Channel:
Channel
Branch    868
ATM       833
Online    811
Name: count, dtype: int64
Total categorías: 3

--------------------------------------------------------------------------------

CustomerOccupation:
CustomerOccupation
Student     657
Doctor      631
Engineer    625
Retired     599
Name: count, dtype: int64
Total categorías: 4

--------------------------------------------------------------------------------

Location (Top 10):
Location
Fort Worth       70
Los Angeles      69
Oklahoma City    68
Charlotte        68
Tucson           67
Philadelphia     67
Omaha            65
Miami            64
Detroit          63
Houston          63
Name: count, dtype: int64
Total ubicaciones únicas: 43

--------------------------------------------------------------------------------

MerchantID (Top 10):
MerchantID
M026    45
M066    34
M065    33
M013    33
M014    33
M028    33
M068    32
M001    32
M070    32
M005    32
Name: count, dtype: int64
Total comercios únicos: 100

## 6. Cardinalidad de Identificadores

Evaluamos la cardinalidad (número de valores únicos) de los campos identificadores para verificar su unicidad y detectar posibles problemas.

In [8]:
print("=" * 80)
print("CARDINALIDAD DE IDENTIFICADORES")
print("=" * 80)

# Columnas identificadoras
columnas_ids = ['TransactionID', 'AccountID', 'DeviceID', 'IP Address', 
                'MerchantID', 'Location']

cardinalidad = {}
for col in columnas_ids:
    if col in df.columns:
        valores_unicos = df[col].nunique()
        total_valores = len(df)
        porcentaje = (valores_unicos / total_valores) * 100
        cardinalidad[col] = {
            'Valores únicos': valores_unicos,
            'Total registros': total_valores,
            'Porcentaje unicidad': f"{porcentaje:.2f}%"
        }
        
resumen_cardinalidad = pd.DataFrame(cardinalidad).T
display(resumen_cardinalidad)

print("\nInterpretación:")
print("- 100% = Cada valor es único (clave primaria)")
print("- <100% = Valores repetidos (pueden ser válidos según el campo)")

================================================================================
CARDINALIDAD DE IDENTIFICADORES
================================================================================

              Valores únicos Total registros Porcentaje unicidad
TransactionID           2512            2512             100.00%
AccountID                495            2512              19.71%
DeviceID                 681            2512              27.11%
IP Address               592            2512              23.57%
MerchantID               100            2512               3.98%
Location                  43            2512               1.71%

Interpretación:
- 100% = Cada valor es único (clave primaria)
- <100% = Valores repetidos (pueden ser válidos según el campo)

## 7. Análisis Temporal

Parseamos las columnas de fechas a formato datetime y analizamos los rangos temporales para entender el periodo cubierto por los datos.

In [9]:
print("=" * 80)
print("ANÁLISIS TEMPORAL")
print("=" * 80)

# TransactionDate
if 'TransactionDate' in df.columns:
    print("\nTransactionDate:")
    print(f"  Tipo de dato original: {df['TransactionDate'].dtype}")
    print(f"  Muestra de valores: {df['TransactionDate'].head(3).tolist()}")
    
    # Parsear a datetime
    transaction_dates = pd.to_datetime(df['TransactionDate'], errors='coerce')
    print(f"\n  Rango temporal:")
    print(f"    - Fecha mínima: {transaction_dates.min()}")
    print(f"    - Fecha máxima: {transaction_dates.max()}")
    print(f"    - Duración: {(transaction_dates.max() - transaction_dates.min()).days} días")
    print(f"  Valores no parseables: {transaction_dates.isna().sum()} ({(transaction_dates.isna().sum()/len(df)*100):.2f}%)")

# PreviousTransactionDate
if 'PreviousTransactionDate' in df.columns:
    print("\n" + "-" * 80)
    print("\nPreviousTransactionDate:")
    print(f"  Tipo de dato original: {df['PreviousTransactionDate'].dtype}")
    print(f"  Muestra de valores: {df['PreviousTransactionDate'].head(3).tolist()}")
    
    # Parsear a datetime
    prev_dates = pd.to_datetime(df['PreviousTransactionDate'], errors='coerce')
    print(f"\n  Rango temporal:")
    print(f"    - Fecha mínima: {prev_dates.min()}")
    print(f"    - Fecha máxima: {prev_dates.max()}")
    if pd.notna(prev_dates.min()) and pd.notna(prev_dates.max()):
        print(f"    - Duración: {(prev_dates.max() - prev_dates.min()).days} días")
    print(f"  Valores no parseables: {prev_dates.isna().sum()} ({(prev_dates.isna().sum()/len(df)*100):.2f}%)")

================================================================================
ANÁLISIS TEMPORAL
================================================================================

TransactionDate:
  Tipo de dato original: object
  Muestra de valores: ['2023-04-11 16:29:14', '2023-06-27 16:44:19', '2023-07-10 18:16:08']

  Rango temporal:
    - Fecha mínima: 2023-01-02 16:00:06
    - Fecha máxima: 2024-01-01 18:21:50
    - Duración: 364 días
  Valores no parseables: 0 (0.00%)

--------------------------------------------------------------------------------

PreviousTransactionDate:
  Tipo de dato original: object
  Muestra de valores: ['2024-11-04 08:08:08', '2024-11-04 08:09:35', '2024-11-04 08:07:04']

  Rango temporal:
    - Fecha mínima: 2024-11-04 08:06:23
    - Fecha máxima: 2024-11-04 08:12:23
    - Duración: 0 días
  Valores no parseables: 0 (0.00%)